"""Terminal output reports for PhantomOrchestra."""

from dataclasses import dataclass, field
from typing import ClassVar

from phantom.signal.report.base import Report

__all__ = [
    "CommandOutputMetadata",
    "CommandOutputReport",
    "NotebookOutputReport",
]


@dataclass
class CommandOutputMetadata:
    """Metadata captured from the shell after a command completes.

    Attributes:
        exit_code: Process exit code; ``-1`` if not yet available.
        pid: Process identifier; ``-1`` if not yet available.
        username: OS username that ran the command.
        hostname: Hostname of the stage container or machine.
        working_dir: Working directory at the time of execution.
    """

    exit_code: int = -1
    pid: int = -1
    username: str | None = None
    hostname: str | None = None
    working_dir: str | None = None


@dataclass
class CommandOutputReport(Report):
    """Report carrying the output of a completed shell command.

    Content is automatically truncated in ``__post_init__`` when it
    exceeds ``MAX_CONTENT_CHARS``, preserving both the head and tail of
    the output with a truncation notice in the middle.

    Attributes:
        command: The shell command that was executed.
        metadata: Exit code, PID, and shell environment metadata.
        hidden: When ``True``, suppress this report from UI display.
        report_type: Fixed discriminator string.
    """

    MAX_CONTENT_CHARS: ClassVar[int] = 30_000

    command: str = ""
    metadata: CommandOutputMetadata = field(
        default_factory=CommandOutputMetadata
    )
    hidden: bool = False
    report_type: str = "command_output"

    def __post_init__(self) -> None:
        """Truncate oversized output immediately after construction."""
        if len(self.content) > self.MAX_CONTENT_CHARS:
            half = self.MAX_CONTENT_CHARS // 2
            omitted = len(self.content) - self.MAX_CONTENT_CHARS
            notice = f"\n[... {omitted} chars truncated ...]\n"
            self.content = self.content[:half] + notice + self.content[-half:]

    @property
    def message(self) -> str:
        """Return a brief summary including exit code."""
        code = self.metadata.exit_code
        return f"Command output (exit={code}): {self.content[:60]}"


@dataclass
class NotebookOutputReport(Report):
    """Report carrying the output of a Jupyter notebook cell.

    Attributes:
        code: Source code that was executed.
        image_urls: URLs of any images generated by the cell.
        report_type: Fixed discriminator string.
    """

    code: str = ""
    image_urls: list[str] = field(default_factory=list)
    report_type: str = "notebook_output"

    @property
    def message(self) -> str:
        """Return a brief summary of the notebook output."""
        imgs = len(self.image_urls)
        return f"Notebook output ({imgs} image(s)): {self.content[:60]}"
